language: node_js

node_js: --lts

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile

script:
  - yarn test
  - yarn lint

after_success:
  - yarn global add codecov
  - codecov

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master

after_script:
  - yarn add -D @codechecks/client @codechecks/build-size-watcher
  - yarn codechecks
